_target_: lightning.pytorch.trainer.Trainer
logger: True
checkpoint_callback: null
enable_checkpointing: True
callbacks: null
default_root_dir: null
gradient_clip_val: null
gradient_clip_algorithm: null
process_position: 0
num_nodes: 1
num_processes: 1
devices: null
auto_select_devices: False
tpu_cores: null
ipus: null
enable_progress_bar: True
overfit_batches: 0.0
track_grad_norm: -1
check_val_every_n_epoch: 1
fast_dev_run: False
accumulate_grad_batches: null
max_epochs: null
min_epochs: null
max_steps: -1
min_steps: null
max_time: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
limit_predict_batches: 1.0
val_check_interval: 1.0
flush_logs_every_n_steps: null
log_every_n_steps: 50
accelerator: null
strategy: null
sync_batchnorm: False
precision: 32
enable_model_summary: True
weights_summary: top
weights_save_path: null
num_sanity_val_steps: 2
resume_from_checkpoint: null
profiler: null
benchmark: False
deterministic: False
reload_dataloaders_every_n_epochs: 0
reload_dataloaders_every_epoch: False
auto_lr_find: False
use_distributed_sampler: True
detect_anomaly: False
auto_scale_batch_size: False
prepare_data_per_node: null
plugins: null
amp_backend: native
amp_level: null
move_metrics_to_cpu: False
multiple_trainloader_mode: max_size_cycle
stochastic_weight_avg: False
terminate_on_nan: null
